name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -m pip install -U pip # to ensure version > 20 to have cache dir
        echo "::set-output name=dir::$(pip cache dir)"
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: py${{ matrix.python-version }}-${{ matrix.os }}-pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install -r requirements.txt
        python -m pip install -e .  # install the repo in editable mode

    - name: EGSnrc pre-reqs
      run: |
        sudo apt-get install -y gfortran gcc g++ make expect

    - name: Cache EGSnrc
      id: cache-EGSnrc
      uses: actions/cache@v2
      with:
        path: ~/EGSnrc
        key: EGSnrc-${{ matrix.os }}


    - name: EGSnrc install
      if: ${{ steps.cache-EGSnrc.outputs.cache-hit != 'true' }}
      run: |
        cd
        git clone --depth 1 https://github.com/nrc-cnrc/EGSnrc.git
        cd EGSnrc
        HEN_HOUSE/scripts/configure.expect actions.conf 3 | tee configure.log
        cd /home/runner/work/egsnrc/egsnrc

    - name: Test with pytest
      run: |
        python -m pip install pytest
