name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-tests:
    strategy:
      matrix:
        # One Python version per OS
        os: [ubuntu, macos]
        python-version: ["3.10"]
        include:
          - os: windows
            python-version: "3.11"
            
    uses: ./.github/workflows/tests.yml
    with: 
      os: ${{ matrix.os }}
      python-version:  ${{ matrix.python-version }}

    
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Check updates to CI tools
        run: |
          echo "| Package  | Version | New Version |" >> $GITHUB_STEP_SUMMARY
          echo "| ---- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| test | 0.1 | 0.2 |" >> $GITHUB_STEP_SUMMARY
