name: tests

on:
  workflow_call:
    inputs:
      os:
        required: true 
        type: string
      python-version:
        required: true 
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.os }}-latest
    steps:
    - name: Check-out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install egsnrc
      run: |
        python -m pip install --editable .

    - name: Test with pytest
      run: |
        python -m pip install pytest pytest-cov
        python -m pytest
